baseURL = 'https://gatekeeperrr.github.io/'
languageCode = 'en-us'
title = 'gatekeeperr'
theme = 'gatekeeperr'

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = 'dracula'
    noClasses = true

disableKinds = ["taxonomy", "term"]

[taxonomies]

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[pagination]
  pagerSize = 6

[params]
  description = "Security research, CTF writeups and blog posts on pwn, malware analysis and reverse engineering."
  tagline = "malware analysis / pwn / rev"
  github = "https://github.com/gatekeeperrr"
  threads = "https://www.threads.net/@gatekeeperr"
  giscusRepo       = "gatekeeperrr/blog_comments"
  giscusRepoId     = "R_kgDOSfPezw"
  giscusCategory   = "General"
  giscusCategoryId = "DIC_kwDOSfPez84C9L2H"
